title: "Juho-Matti Kilpeläinen"
description: ""
url: "https://kilpelainenj.com"
baseurl: ""

theme: minima

author: ""

minima:
  skin: classic 
  nav_pages:
    - index.md
    - blog.md
    - about.md
