title: "Juho-Matti Kilpeläinen"
description: ""
url: "https://kilpelainenj.com"
baseurl: ""

theme: minima
google_analytics: "G-F4XPJ5X1EC"
author: ""

minima:
  skin: classic 
  nav_pages:
    - index.md
    - blog.md
    - about.md
